# Generated by Django 4.1 on 2023-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=50)),
                ("pwd", models.CharField(max_length=255)),
                ("salt", models.CharField(max_length=255)),
                ("isDelect", models.BooleanField(choices=[(1, "注销"), (0, "登记")])),
                ("datetime", models.TimeField()),
            ],
        ),
    ]
